### ISSUE TITLE
Broken styling

### ISSUE THREAD

**Issue by danbruegge** [ltGuillaume/FeedMei#1]
Hi, after copying themes.local from the current master into my installation and selecting the any feedmei theme, the styling gets broken.

![image](https://user-images.githubusercontent.com/1296438/82654343-dd113380-9c20-11ea-8f41-7010caa48c87.png)

My ttrss is also on the current master. Any idea? Do you need any additional information?

**Comment by ltGuillaume** [comment]
Hi!

![image](https://user-images.githubusercontent.com/4777345/82667923-0fc72600-9c39-11ea-9de3-b5e1db883e9f.png)

I'm getting the same thing _if the file `/tt-rss/themes/light.css`_ can't be found. Did you by any chance delete it?

**Comment by danbruegge** [comment]
![image](https://user-images.githubusercontent.com/1296438/82682009-dac5ce00-9c4e-11ea-9e7d-6a7feb040e73.png)
Maybe the problem is, symlinked the themes.local folder.
I did a clone of your project and created an symlink. If i copy the folder directly into my ttrss instance, it works.

**Comment by ltGuillaume** [comment]
That would be the reason yes, 100%. You'll need to give PHP access to the folder the symlink links to, as well, e.g. via `fastcgi_param PHP_VALUE open_basedir="/srv/somedir/";` if you're using nginx, or if you use Docker, dive into the the documentation to find how a similar thing can be done.
