### ISSUE TITLE
A Way to leave the color in the icons?

### ISSUE THREAD

**Issue by Zottelchen** [ltGuillaume/FeedMei#2]
Hi,

I really like the FeedMei_Night theme, thank you for that :)

However, is there a way to have the feed icons colored?

**Comment by ltGuillaume** [comment]
Hi! Sure you can, by changing this line in `feedmei.css`:
https://github.com/ltGuillaume/FeedMei/blob/3d822da7f52c67d2b6545926b39d67fe1e70ec84/themes.local/feedmei.css#L169
to either
```
 .header img { opacity(75%) !important } 
```
or
```
 .header img { } 
```
(whatever you like most)

**Comment by Zottelchen** [comment]
Thank you, the colors are back, but they are inverted now. Any fix for that? Also the checkmarks in front of article titles got a lot brighter and don't really fit the dark theme. 
![image](https://user-images.githubusercontent.com/5148555/105563701-654f5780-5d1f-11eb-9cb0-ef55a0e66f52.png)

**Comment by ltGuillaume** [comment]
Ok, that makes sense, I wasn't paying attention and forgot you were using the night theme, sorry!

Ok, in that case, please revert the change I suggested before and add the following to `feedme_night.css`:
```
body.ttrss_main img.icon,
#headlines-frame img.icon { filter: grayscale(0%) invert(100%) !important }
```

**Comment by Zottelchen** [comment]
Thank you so much! :) The checkmarks are still bright, but I like this a lot better!

**Comment by ltGuillaume** [comment]
Like in your screenshot? Are you sure you reverted the earlier change properly? (just overwrite `feedmei.css` with the latest version from here to be sure).

**Comment by Zottelchen** [comment]
You're right, it is fixed now 😅 Probably should have done a force refresh.

However I found 2 other issues:
1. Article header images for some feeds are now inverted.
![](https://user-images.githubusercontent.com/5148555/105748597-a5425480-5f42-11eb-9e88-cb91fab1b57c.png)
2. YouTube videos are inverted - but only when in fullscreen.
![](https://user-images.githubusercontent.com/5148555/105748801-e8042c80-5f42-11eb-8026-c7544d1f1f8e.png)

**Comment by ltGuillaume** [comment]
Ok, we need to isolate the cause of this issue. Was this the case before the change made for the colored icons? Can you undo the change (just comment it out by putting it between `/*` and `*/`) and see what happens.

**Comment by Zottelchen** [comment]
I've just restored your original files to check if I messed up something, but no it seems to be an actual issue with the dark theme. Can you reproduce this on your instance? Do you need an rss affected?

**Comment by ltGuillaume** [comment]
Yes, I'd like an RSS that's affected. I'll look at it later!

**Comment by Zottelchen** [comment]
Here a generated rss feed with some articles and a video: https://rss.zeropoly.de/public.php?op=rss&id=nightmodedebugging&key=u2carj600ff93519d0c

**Comment by ltGuillaume** [comment]
Could you try this one?

[feedmei_night.zip](https://github.com/ltGuillaume/FeedMei/files/5876354/feedmei_night.zip)

**Comment by ltGuillaume** [comment]
Can you try this one?
[feedmei_night.zip](https://github.com/ltGuillaume/FeedMei/files/5876365/feedmei_night.zip)

**Comment by Zottelchen** [comment]
This recolored the icons, but the content images/fullscreen youtube videos are still inverted.

**Comment by ltGuillaume** [comment]
Really? That's strange, it worked for me. Probably a difference in browser interpretation. Did you press Ctrl+F5 or cleared your cache? It might be that your browser uses the previous version.

**Comment by Zottelchen** [comment]
The problem still exists for me with Chrome and Firefox and Brave (a browser I haven't used before)...

**Comment by ltGuillaume** [comment]
Thx for checking all those browsers. I think you have some ttrss plugins enabled that I haven't, because in the test feed you sent, there was only one image that had its colors inverted, which I fixed. I also applied other changes for (full-screen) video, but there were no embedded videos in the feed for me.

Which plugins are you using?

**Comment by Zottelchen** [comment]
I use the following plugins:

- auth_internal
- af_comics
- af_redditimgur
- af_tumblr_1280
- af_unburn
- af_youtube_embed
- af_zz_noautoplay
- cache_starred_images
- feediron
- feedstatistics
- note
- tumblr_gdpr_ua

**Comment by Zottelchen** [comment]
Just checked with a clean install of TTRSS - images are indeed no longer inverted. So that seems to be a problem with my instance :/

**Comment by Zottelchen** [comment]
I don't get what is causing this. I've compared the css files (base themes as well as themes.local) with the current up2date ones as well as those on my clean install - nothing. I've logged in safe mode (without plugins) - nothing. Just why...🤔

**Comment by ltGuillaume** [comment]
Wow, I'm loving how you want to get to the bottom of this, thank you for that!

Do you have the same plugins enabled in both instances? I don't think I can conclude that from what you posted just yet.

**Comment by Zottelchen** [comment]
I've just tried installing/using the same plugins, but that doesn't seem to change anything.

**Comment by ltGuillaume** [comment]
> I've just tried installing/using the same plugins, but that doesn't seem to change anything.

So that means it works now? Including full-screen video?

**Comment by Zottelchen** [comment]
I've made a mistake yesterday and checked the wrong feed on the fresh instance... Even on the fresh instance without plugins the images are inverted.

**Comment by ltGuillaume** [comment]
Yes, that would be really nice to check. Would they have the affected feed(s) in them?
If you use credentials, how do you want to share them? You could [put them here](https://bin.disroot.org/) and check "Burn after reading".

**Comment by Zottelchen** [comment]
Yes, i've added a few feeds to the user.

https://bin.disroot.org/   ?bd6bbc6de60356b1#3p4oT2dfWCH6F6iuamrBFMozWAo1WnE9h2iae5C98KiZ

Normal instance: rss.zeropoly.de
Test instance: rss2.zeropoly.de:8280 (default port of the docker container)

**Comment by ltGuillaume** [comment]
Thanks!

I've fixed the header images and the YouTube embedded videos, tested on your normal instance. See latest commit.
What I'm _not_ yet sure about is whether directly embedded videos (so with the `<video>` tag) will still be inverted. If you have a feed that embeds non-YouTube videos directly, we can test that, too.

**Comment by Zottelchen** [comment]
Took a moment, because I didn't have such a feed - but I created one. Check it out on the live instance (I also updated to your current CSS).

**Comment by ltGuillaume** [comment]
No you're really fast! Thanks, the latest commit should fix everything I've seen then 🙂

Don't forget to include the following again after updating, then you should be all set.
```
body.ttrss_main img.icon,
#headlines-frame img.icon { filter: grayscale(0%) invert(100%) !important }
```

**Comment by Zottelchen** [comment]
Thank you very much! :) Everything is now working as expected 👍

**Comment by ltGuillaume** [comment]
Great! Thanks for helping me figure this out! 👍
